language: node_js
cache: npm
node_js:
- '14.4'
install:
  - npm install
test:
  - npm run test-ci
deploy:
  on:
    tags: true
  provider: npm
  email: itamarjr91@gmail.com
  api_key:
    secure: J/fRqMekNxLAbVRiM7yew5iLktfQmu5nyHAu97EDBOKDCKC7+OFinWfDj47fbWAr8vbTDpgOF+s+8/uNIpJVsn2Lpkhz02ftPWE48CJW37D1KZ4z+M44NA3c/axiwA0hSLFu8HDwu8yKDMyaAvWtPXaY3TB9rAF+T6O98YIcOrvaj6ZADIcSN0VqhFxKHpVppI2uwiIWZ/lIQBwGVO1vnpCeeI5x7IK0y5Y5ifWKMZ71zszBBH/qzXflOfZ53mgjEIjk7U1C2UoIgL2LOM9QPAqFXTC6RL7+TDTTH66J5bXBT9YykYctaLjLB2QlWIbIXtiMNo4GkYhWrvxeITXXcUlxM4U1/Z+OsRFA6sGTzINkGi40GEWnvgISFFGhcTUKhMv6/uHMzHzLuRnPb7pbD56/60YddsQuPCED8jGFd3AEarCwaxd5jDeNcFneQU98RB0eoTkRGac12ojFQWtdIVDeestKVmXmte60nibPJP36kpBsIxdtOae6UjRuVG1bPu6lpkJ9pXrJ1u2Shr3MOqzb5hr7YAZ2CYeGjhshRq42mbtX/J3vtMuhipGC+QkYvrPOQMm3H+HwzxmqdpIPOOGJT22iSGfQmv+17p6CZmBDIdE3Y9xIQAHsDNUZsE8EtoRK4+zUk0/xrbQoEsSp+tFKWbjaRM845swYLv1t0iY=
